
name = "toni-link-preview"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "./.cloudflare/workers-site"

[build]
command = "npm install && npm run build"
